spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: admin
      database: Bancos-DEV
      host: localhost
      port: 27017

controller:
  uri: /api/v1/bancos/coordenadas/

client:
  coordenadas:
    name: Bancos-Json
    url: localhost:9090
    uri: /api/v1/legacy/bancos/coordinates

header:
  accept:
    name: accept
  uuid:
    name: uuid 
  countryCode:
    name: countrycode
  channelId:
    name: channelid
  businessCode:
    name: businesscode
  messages:
    missingHeader: Missing Header

requestParams:
  coordX:
    name: gpsCoordX
  coordY:
    name: gpsCoordY
  messages:
    missingParam: Missing request param

exceptions:
  message: 
    notfound: NOT FOUND
    badrequest: BAD REQUEST
    invalidHeader: INVALID HEADER
    invalidRequestParam: INVALID REQUEST PARAMETER
  location:
    service: Service
    controller: Controller
    dao: DAO
