spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: admin
      database: Bancos-DEV
      host: localhost
      port: 27017

controller:
  uri: /api/v1/bancos/coordenadas/

client:
  coordenadas:
    name: Bancos-Json
    url: localhost:9090
    uri: /api/v1/legacy/bancos/coordinates

exceptions:
  message: 
    notfound: NOT FOUND
    badrequest: BAD REQUEST
  location:
    service: Service
    controller: controller
