spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: admin
      database: Bancos-SIT
      host: localhost
      port: 27017

controller:
  uri: /api/v1/bancos/estado/{state}

client:
  estado:
    name: Bancos-Json
    url: localhost:9090
    uri: /api/v1/legacy/bancos/estado/{estado}

exceptions:
  message: 
    notfound: NOT FOUND
    badrequest: BAD REQUEST
  location:
    service: Service
    controller: controller
