spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: admin
      database: tareas
      host: localhost
      port: 27017
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/tarea_dto
    username: postgres
    platform: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
#    hibernate:
#      ddl-auto: create